/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_workflows__name__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Books */
        get: operations["get_books_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book Runs */
        get: operations["get_book_runs_books__book_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Files */
        get: operations["get_files_books__book_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_books__book_id__files__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/voice-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Voice Assignments */
        patch: operations["patch_voice_assignments_books__book_id__voice_assignments_patch"];
        trace?: never;
    };
    "/books/{book_id}/chapters/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chapter */
        get: operations["get_chapter_books__book_id__chapters__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/chapters/{number}/beats/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Beat */
        patch: operations["patch_beat_books__book_id__chapters__number__beats__index__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BeatPatch
         * @description A change to one beat: any of its speaker, text, or emotion. Unset fields are left as-is.
         */
        BeatPatch: {
            /** Character Id */
            character_id?: number | null;
            /** Text */
            text?: string | null;
            /** Emotion */
            emotion?: string | null;
        };
        /**
         * BeatView
         * @description One AI-produced beat with its resolved speaker, for the attribution review.
         */
        BeatView: {
            /** Index */
            index: number;
            /** Character Id */
            character_id?: number | null;
            /** Character Name */
            character_name: string;
            /** Beat Type */
            beat_type: string;
            /** Text */
            text: string;
            /** Emotion */
            emotion?: string | null;
        };
        /**
         * BookDetail
         * @description A book's metadata, chapters, characters, and recorded voice assignments.
         */
        BookDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Chapters */
            chapters: components["schemas"]["ChapterSummary"][];
            /** Characters */
            characters: components["schemas"]["CharacterInfo"][];
            /** Voice Assignments */
            voice_assignments: {
                [key: string]: string;
            };
        };
        /**
         * BookSummary
         * @description A book's headline metadata and casting counts for the list view.
         */
        BookSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Language */
            language?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Chapters */
            chapters: number;
            /** Characters */
            characters: number;
            /** Cast */
            cast: number;
        };
        /**
         * BooksResponse
         * @description The known books with their metadata.
         */
        BooksResponse: {
            /** Books */
            books: components["schemas"]["BookSummary"][];
        };
        /**
         * CastMember
         * @description A speaker in a chapter and how many beats they carry, for the cast legend.
         */
        CastMember: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /**
         * ChapterDetail
         * @description A chapter's parsed sections beside its beats and cast, for the attribution review.
         */
        ChapterDetail: {
            /** Number */
            number: number;
            /**
             * Title
             * @default
             */
            title: string;
            /** Sections */
            sections: components["schemas"]["SectionView"][];
            /** Beats */
            beats: components["schemas"]["BeatView"][];
            /** Cast */
            cast: components["schemas"]["CastMember"][];
        };
        /**
         * ChapterSummary
         * @description One chapter's number, title, and how many beats have been extracted.
         */
        ChapterSummary: {
            /** Number */
            number: number;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Beats
             * @default 0
             */
            beats: number;
        };
        /**
         * CharacterInfo
         * @description A character and the voice traits the AI assigned.
         */
        CharacterInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Gender */
            gender?: string | null;
            /** Age */
            age?: string | null;
            /** Accent */
            accent?: string | null;
        };
        /**
         * FilesResponse
         * @description Relative paths of a book's artifact files.
         */
        FilesResponse: {
            /** Files */
            files: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness signal for the platform.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * RunLogsResponse
         * @description A page of run log lines and the cursor to fetch the next page.
         */
        RunLogsResponse: {
            /** Lines */
            lines: string[];
            /** Cursor */
            cursor: number;
            /** Done */
            done: boolean;
        };
        /**
         * RunRequest
         * @description Body for starting a workflow run.
         */
        RunRequest: {
            /** Url */
            url: string;
            /**
             * Start Chapter
             * @default 1
             */
            start_chapter: number;
            /** End Chapter */
            end_chapter?: number | null;
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
            /** Provider */
            provider?: string | null;
            /** Book Id */
            book_id?: string | null;
        };
        /**
         * RunStatusResponse
         * @description The state of a workflow run.
         */
        RunStatusResponse: {
            /** Run Id */
            run_id: string;
            /** Workflow */
            workflow: string;
            /** State */
            state: string;
            /** Returncode */
            returncode?: number | null;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
        };
        /**
         * RunSummary
         * @description One run's state for a book, so the chapters table can show live progress.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Workflow */
            workflow: string;
            /** Start Chapter */
            start_chapter?: number | null;
            /** End Chapter */
            end_chapter?: number | null;
            /** State */
            state: string;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
        };
        /**
         * RunsResponse
         * @description The runs recorded for a book, oldest first.
         */
        RunsResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * SectionView
         * @description One parsed source paragraph from the input snapshot.
         */
        SectionView: {
            /** Text */
            text: string;
            /** Section Type */
            section_type?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    start_run_workflows__name__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_runs__run_id__logs_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_books_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooksResponse"];
                };
            };
        };
    };
    get_book_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_runs_books__book_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_books__book_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_books__book_id__files__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_voice_assignments_books__book_id__voice_assignments_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_books__book_id__chapters__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_beat_books__book_id__chapters__number__beats__index__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                number: number;
                index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeatPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
